title: AI course
tagline: Deep Learning Lecture

author:
  name: LEE-YUYU
  url: https://www.facebook.com/profile.php?id=100004518336688

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

paginate: 3

tags_path: /tags/
categories_path: /categories/

remote_theme: zivong/jekyll-theme-hydure
#theme: jekyll-theme-hydure
